In [4]:
# importing Numpy
import numpy as np

print (np.__version__)               # this prints the version of the numpy

#np.show_config()                    # this prints  or shows the config of numpy

1.13.3


In [ ]:
#printing zero matrix
s= np.zeros(5)
z= np.zeros([3,5])
print(s)
print(z)

In [57]:
# print shape of a matrix
print(z.shape)

# print no. of elements
print(z.shape)

#print size of each elelment
print(z.itemsize)

#print datatype of matrix
print(z.dtype)

#print dimension of a matrix
print(z.ndim)

#reshaping a matri(no of elements should match)
z.reshape(5,3)
print(z)


#PRINTING MEMORY SIZE OF A MATRIX
print("%d bytes" %(z.size* z.itemsize)) 


(3, 5)
(3, 5)
8
float64
2
[[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]]
120 bytes


In [6]:
#CREATING VECTORS
a1=np.arange(2,9)
print(a1)

x3= np.arange(18).reshape(3,6)
print("arange with reshape")
print(x3)

#CREATING A MATRIX
print("   MATRIX   ")
a2= np.arange(12)
a2=a2.reshape(3,4)
print(a2)

[2 3 4 5 6 7 8]
arange with reshape
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
   MATRIX   
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [39]:
#Reversing the matrix
a = a2 # remember chages needs to be saved  other wise they are lost (numpy view look)
a= a[::-1]
print(a)

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [43]:
#making a in=dentical matrix
iden= np.eye(3)
print(iden)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [49]:
#FINDING MAX,MIN,MEAN,STD OF A MATRIX
a.max(),a.min(),a.mean(),a.std()


(11, 0, 5.5, 3.4520525295346629)

In [63]:
#using random to gnrate matrix
q1=np.random.random(30)
q2=np.random.random((3,3))#3x3 matrix
q3=np.random.random((3,3,3))

print("random 30 ")
print(q1)
print("random 3x3 matrix ")
print(q2)
print("random 3x3x3")
print(q3)


random 30 
[ 0.21192311  0.82957251  0.91917284  0.55678821  0.07507897  0.15588682
  0.38740569  0.65584362  0.13097225  0.35158857  0.00699983  0.90212585
  0.54641185  0.32920389  0.5001179   0.32815656  0.66451476  0.69648921
  0.94879892  0.09181699  0.52698939  0.94227871  0.41010882  0.62335872
  0.51443766  0.03578491  0.75916916  0.26598822  0.40294611  0.18094525]
random 3x3 matrix 
[[ 0.34718501  0.11896689  0.54375326]
 [ 0.48227313  0.19914625  0.83975837]
 [ 0.1860705   0.24849519  0.69142289]]
random 3x3x3
[[[ 0.69292098  0.89414958  0.6590756 ]
  [ 0.66422677  0.5651913   0.21081127]
  [ 0.91476574  0.6445105   0.73069175]]

 [[ 0.44560996  0.71626859  0.83214018]
  [ 0.06654657  0.71430577  0.13971332]
  [ 0.9209538   0.30522526  0.9838162 ]]

 [[ 0.28106479  0.14568827  0.75181071]
  [ 0.68803402  0.0766066   0.6756939 ]
  [ 0.66991303  0.87729433  0.69703197]]]
